### ISSUE TITLE
Implement generic smooth transition example

### ISSUE THREAD

**Issue by qwiglydee** [qwiglydee/otree-front#119]
Implement generic `transitDisplays` to use instead of `ot.switchDisplays`, with the same on/off args as of #118

```css
.fade-out {
  opacity: 0;
  transition: opacity 100ms easy-out;
}

fade-in {
  opacity: 1;
  transition: opacity 50ms easy-in;
}
```

```javascript
function transitDisplays(switching_params) {
  // put fade-out class to off-elems
  // delay switchDisplay by fadeout time, with the same params
  // schedule putting fade-in class to on-elems
})
```

Try it on multistage example and for global trials transition, and in combination of both
